Fix metadata issue multitok.py
Fix issue
AttributeError: 'str' object has no attribute 'items'
headers cannot be a string, but needs to be an object